### YamlMime:Landing
title: Documentatie voor Docker op Azure
summary: Docker is een populair platform voor containerbeheer en beeldbewerking waarmee u snel met containers op Linux en Windows kunt werken. Meer informatie over het gebruiken van Docker op Azure.
metadata:
  title: Documentatie voor Docker op Azure
  description: Docker is een populair platform voor containerbeheer en beeldbewerking waarmee u snel met containers op Linux en Windows kunt werken.
  services: multiple
  ms.service: multiple
  ms.topic: landing-page
  author: georgewallace
  ms.author: gwallace
  ms.date: 03/08/2020
  ms.openlocfilehash: 94d5dd74aad11e2271de52dd082cfb9287eb10c1
  ms.sourcegitcommit: 152c522bb5ad64e5c020b466b239cdac040b9377
  ms.translationtype: HT
  ms.contentlocale: nl-NL
  ms.lasthandoff: 08/14/2020
  ms.locfileid: "88224574"
landingContent:
- title: Docker op Azure implementeren
  linkLists:
  - linkListType: overview
    links:
    - text: Docker implementeren in Ubuntu Quickstart-sjabloon
      url: https://azure.microsoft.com/resources/templates/docker-simple-on-ubuntu/
- title: Aan de slag
  linkLists:
  - linkListType: tutorial
    links:
    - text: Een Python-web-app (Django) uitvoeren met PostgreSQL in Azure App Service
      url: ../app-service/tutorial-python-postgresql-app.md
    - text: Een infrastructuur voor ontwikkeling maken op een Linux-VM in Azure met Jenkins, GitHub en Docker
      url: ../jenkins/tutorial-jenkins-github-docker-cicd.md
- title: Resources
  linkLists:
  - linkListType: reference
    links:
    - text: Docker Azure-site
      url: https://docs.docker.com/docker-for-azure/why/
    - text: Docker Azure-stuurprogramma
      url: https://docs.docker.com/machine/drivers/azure/
    - text: Meer informatie over Docker
      url: https://docker.com
