- name: Documentatie voor Docker
  href: index.yml
- name: Snelstartgids
  expanded: true
  items:
    - name: Een Ubuntu-VM implementeren met Docker
      href: 'https://azure.microsoft.com/resources/templates/docker-simple-on-ubuntu/'
- name: Zelfstudies
  items:
    - name: Python-webtoepassing met Docker en PostgreSQL
      href: ../app-service/containers/tutorial-python-postgresql-app.md?toc=%2fazure%2fpostgresql%2ftoc.json
    - name: 'CI/CD met Docker, Jenkins en Linux'
      href: /azure/jenkins/tutorial-jenkins-github-docker-cicd
- name: Instructiegidsen
  items:
    - name: Docker-VM-extensie
      href: /azure/virtual-machines/linux/dockerextension
    - name: Docker Machine
      href: /azure/virtual-machines/linux/docker-machine
    - name: Docker-containerregister
      href: /azure/container-registry/container-registry-get-started-portal
- name: Resources
  items:
    - name: Azure-roadmap
      href: 'https://azure.microsoft.com/roadmap/'
    - name: Docker Azure-stuurprogramma
      href: 'https://docs.docker.com/machine/drivers/azure/'
    - name: Docker Azure-site
      href: 'https://www.docker.com/docker-azure'
    - name: Docker-site
      href: 'https://docker.com'