### YamlMime:Landing
title: Documentatie voor Azure AD-rollen - Azure AD
summary: Met op rollen gebaseerd toegangsbeheer in Azure AD wordt de toegang tot Azure AD-resources beheerd. Maak aangepaste rollen, wijs rollen toe die gebruikmaken van beheereenheden om het beheerbereik te beperken, wijs toegang tot toepassingen toe aan groepen of gebruikers, beheer wie in aanmerking komt met PIM (Privileged Identity Management), of delegeer machtigingen om identiteitsbeheertaken te verdelen.
metadata:
  title: Documentatie voor Azure Active Directory-rollen
  description: Meer informatie over het gebruik van Azure AD-rollen voor het beheren van de toegang in uw organisatie.
  services: active-directory
  ms.service: active-directory
  ms.subservice: roles
  manager: daveba
  ms.topic: landing-page
  ms.date: 10/19/2020
  author: curtand
  ms.author: curtand
  ms.openlocfilehash: 8dd6ac6fef0dbc84c77ccacfd048b2af21771f6a
  ms.sourcegitcommit: d60976768dec91724d94430fb6fc9498fdc1db37
  ms.translationtype: HT
  ms.contentlocale: nl-NL
  ms.lasthandoff: 12/02/2020
  ms.locfileid: "96499200"
landingContent:
- title: Over Azure AD-rollen
  linkLists:
  - linkListType: overview
    links:
    - text: Overzicht van op rollen gebaseerd toegangsbeheer van Azure AD
      url: custom-overview.md
  - linkListType: concept
    links:
    - text: Inzicht in de Azure AD-rollen
      url: concept-understand-roles.md
    - text: Beheereenheden in Azure AD begrijpen
      url: administrative-units.md
    - text: Cloudgroepen gebruiken om roltoewijzingen te beheren
      url: groups-concept.md
- title: Aan de slag
  linkLists:
  - linkListType: quickstart
    links:
    - text: Machtigingen verlenen voor onbeperkte app-registraties
      url: quickstart-app-registration-limits.md
- title: Rollen delegeren
  linkLists:
  - linkListType: how-to-guide
    links:
    - text: Rollen per taak delegeren
      url: delegate-by-task.md
    - text: Mobiel toepassingsbeheer delegeren
      url: delegate-app-roles.md
- title: Rollen toewijzen aan gebruikers
  linkLists:
  - linkListType: how-to-guide
    links:
    - text: Aangepast rollen maken
      url: custom-create.md
    - text: Rollen toewijzen met Graph API
      url: custom-assign-graph.md
    - text: Toewijzen met behulp van PowerShell
      url: custom-assign-powershell.md
    - text: Rollen toewijzen met Graph API
      url: custom-assign-graph.md
- title: Rollen toewijzen aan groepen
  linkLists:
  - linkListType: how-to-guide
    links:
    - text: Groepen maken waaraan rollen kunnen worden toegewezen
      url: groups-create-eligible.md
    - text: Een rol toewijzen aan een cloudgroep
      url: groups-assign-role.md
    - text: Zorgen dat een groep in aanmerking komt voor PIM
      url: groups-pim-eligible.md
    - text: Toewijzingen voor een groep weergeven
      url: groups-view-assignments.md
- title: Bereik met beheereenheden beheren
  linkLists:
  - linkListType: how-to-guide
    links:
    - text: Beheereenheden toevoegen en verwijderen
      url: admin-units-manage.md
    - text: Gebruikers toewijzen aan eenheden
      url: admin-units-add-manage-users.md
    - text: Groepen toewijzen aan eenheden
      url: admin-units-add-manage-groups.md
    - text: Groepen met bereik toewijzen
      url: admin-units-assign-roles.md
